-- GROUPING SETS
-- Crear grupos dentro de grupos o generar grupos individuales

SELECT DEPARTMENT_ID, SUM(SALARY) AS "Salario total"
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY GROUPING SETS(DEPARTMENT_ID)
ORDER BY DEPARTMENT_ID;


-- Agrupa primero por department_id y luego por job_id
SELECT DEPARTMENT_ID,JOB_ID, SUM(SALARY) AS "Salario total"
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY GROUPING SETS(DEPARTMENT_ID,JOB_ID)
ORDER BY DEPARTMENT_ID;