-- INLINE VIEW

CREATE VIEW VISTA_EMPLE AS SELECT * FROM EMPLOYEES ORDER BY SALARY DESC;

SELECT * FROM VISTA_EMPLE WHERE SALARY > 5000;

-- vistas inline

SELECT FIRST_NAME,SALARY FROM (SELECT * FROM EMPLOYEES ORDER BY SALARY DESC) WHERE SALARY > 5000;


-- INSERT EN VISTAS INLINE

CREATE TABLE REGIONES1 AS SELECT * FROM REGIONS;

SELECT * FROM REGIONES1;

CREATE VIEW VIEW_REGIONES AS SELECT * FROM REGIONES1;

INSERT INTO VIEW_REGIONES VALUES(5,'ANTARTICA');

INSERT INTO (SELECT * FROM REGIONES1) VALUES(6,'AUSTRALIA');


-- UPDATE EN VISTAS INLINE
UPDATE (SELECT * FROM REGIONES1 WHERE REGION_ID > 3)  SET REGION_NAME = LOWER(REGION_NAME);







