--ROLLUP Y CUBE

SELECT DEPARTMENT_ID, SUM(SALARY) AS "Salario total"
FROM EMPLOYEES 
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY ROLLUP(DEPARTMENT_ID); -- Agrega una sumatoria total al final


SELECT CITY, DEPARTMENT_NAME, COUNT(*) AS "Empleados"
FROM LOCATIONS 
NATURAL JOIN DEPARTMENTS  
JOIN EMPLOYEES 
    USING (DEPARTMENT_ID)
GROUP BY CUBE(CITY,DEPARTMENT_NAME)
ORDER BY CITY,DEPARTMENT_NAME;