/*
  PARTICIONAMIENTO POR LISTA
  
  PARTITION BY LIST (columna,columna1)
  (
      PARTITION P1 VALUES (V1,V2),
      PARTITION P2 VALUES (V1,V2),
      PARTITION P3 VALUES (V1,V2,V3),
      PARTITION P4 VALUES (DEFAULT),


      
  
  */

/* ---------------------------------------------------------------------------*/
CREATE TABLE LISTA (	
    CODIGO NUMBER NOT NULL, 
	PAIS VARCHAR2(100),
    CLIENTE VARCHAR2(100)
) 
  PARTITION BY LIST (PAIS)(
      PARTITION EUROPA VALUES ('ESPAÑA','FRANCIA','ALEMANIA'),
      PARTITION LATINOAMERICA VALUES ('ARGENTINA','CHILE'),
      PARTITION ASIA VALUES ('MALASIA','CHINA','INDONESIA')
);
     
     
SELECT * FROM USER_TAB_PARTITIONS WHERE TABLE_NAME = 'LISTA';
     
INSERT INTO LISTA VALUES (1,'FRANCIA','CLIENTE1');

SELECT * FROM LISTA;

SELECT * FROM LISTA PARTITION (EUROPA);
     
UPDATE LISTA SET PAIS = 'CHINA' WHERE PAIS = 'FRANCIA';
     
ALTER TABLE LISTA ENABLE ROW MOVEMENT;