--Fusionar particiones

ALTER TABLE LISTA MERGE PARTITIONS LATINOAMERICA, AMERICA_NORTE INTO PARTITION AMERICA;

SELECT * FROM USER_TAB_PARTITIONS WHERE TABLE_NAME = 'LISTA';



-- Crear tablas Hash

CREATE TABLE HASH_TABLE (
    CODIGO NUMBER NOT NULL,
    DATOS VARCHAR2(100)
)
    PARTITION BY HASH(CODIGO)
    PARTITIONS 3;
    

SELECT * FROM USER_TAB_PARTITIONS WHERE TABLE_NAME = 'HASH_TABLE';


-- Borrar particiones

ALTER TABLE RANGO
DROP PARTITION p3_4;




