
-- Tabla normal e indice particiONado

DROP TABLE T1;

CREATE TABLE T1
(CODIGO NUMBER,
DATOS VARCHAR2(50));

CREATE INDEX G1_T1 ON T1 (CODIGO) GLOBAL PARTITION BY HASH(CODIGO) PARTITIONS 4;

SELECT * FROM USER_IND_PARTITIONS WHERE INDEX_NAME = 'G1_T1';



-- Tabla particionada e indice normal

DROP TABLE t2;
CREATE TABLE t2
(CODIGO NUMBER,
DATOS VARCHAR2(50))
PARTITION BY RANGE (CODIGO)
  (
      PARTITION P1 VALUES LESS THAN (10),
      PARTITION P2 VALUES LESS THAN (20),
      PARTITION P3 VALUES LESS THAN (30),
      PARTITION P4 VALUES LESS THAN (40)
);
     
CREATE INDEX T2_I1 ON t2(DATOS);
     
     
-- Tabla particiONada e índice global particiONado

DROP TABLE T3;
CREATE TABLE T3
(CODIGO NUMBER,
DATOS VARCHAR2(50))
PARTITION BY RANGE (CODIGO)
  (
      PARTITION P1 VALUES LESS THAN (10),
      PARTITION P2 VALUES LESS THAN (20),
      PARTITION P3 VALUES LESS THAN (30),
      PARTITION P4 VALUES LESS THAN (40)
);
        
CREATE INDEX G1_T3 ON T3 (DATOS) GLOBAL PARTITION BY HASH(DATOS) PARTITIONS 4;
     
-- indices particiONados LOCALes

DROP TABLE T4;
CREATE TABLE T4
(CODIGO NUMBER,
DATOS VARCHAR2(50))
PARTITION BY RANGE (CODIGO)
  (
      PARTITION P1 VALUES LESS THAN (10),
      PARTITION P2 VALUES LESS THAN (20),
      PARTITION P3 VALUES LESS THAN (30),
      PARTITION P4 VALUES LESS THAN (40)
     );
     
CREATE INDEX T4_I1 ON T4(CODIGO) LOCAL ;
SELECT * FROM USER_IND_PARTITIONS WHERE INDEX_NAME='T4_I1';
