-- Particiones compuestas
CREATE TABLE RANGO_SUB (	
    CODIGO NUMBER NOT NULL , 
	DATOS VARCHAR2(100)	,
    FECHA date,
    COD_CLIENTE NUMBER
) 
  PARTITION BY RANGE (FECHA)
     SUBPARTITION BY HASH(COD_CLIENTE) SUBPARTITIONS 3
  (
    PARTITION TIMESTRE1 VALUES LESS THAN (TO_DATE('01-04-2023','dd-mm-yyyy')),
    PARTITION TIMESTRE2 VALUES LESS THAN (TO_DATE('01-07-2023','dd-mm-yyyy')),
    PARTITION TIMESTRE3 VALUES LESS THAN (TO_DATE('01-10-2023','dd-mm-yyyy')),
    PARTITION TIMESTRE4 VALUES LESS THAN (TO_DATE('01-01-2024','dd-mm-yyyy'))
);

SELECT * FROM USER_TAB_PARTITIONS WHERE TABLE_NAME = 'RANGO_SUB';
SELECT * FROM USER_TAB_SUBPARTITIONS WHERE TABLE_NAME = 'RANGO_SUB';
